# Generated by Django 3.1.7 on 2021-03-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=80)),
                ('experience', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=80)),
                ('department', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('qa', 'QA')], max_length=80)),
                ('joined', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
